spring:
  application:
    name: gateway  
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
      routes:
      - id: master-file
        uri: lb://master-file 
        predicates:
        - Path=/api/master-files/**
      - id: fare
        uri: lb://fare
        predicates:
        - Path=/api/fare/**
      - id: schedule
        uri: lb://schedule
        predicates:
        - Path=/api/schedule/**
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: ${JAEGER_URI:http://jaeger-collector.istio-system.svc.cluster.local:4317}
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - prometheus 
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8080/eureka
discovery:
  locator:
    enabled: true   
    lower-case-service-id: true    